lint_task:
  container:
    image: python:3.7-slim
  install_script:
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint --version
    - pylint ./lib

success_task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - lint
