# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
# Set to False to stop trying to change ~= to ==
pin: False

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every week"
