# Settings in the [build] context are global and are applied to 
# all contexts unless otherwise overridden by more specific contexts.
[build]
  publish = "build/dirhtml/"
  command = "make dirhtml"
  environment = { PYTHON_VERSION = "3.8" }

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
